### ISSUE TITLE
Let's not lock the rotation

### ISSUE THREAD

**Issue by sleepylee** [kodeba/surveys-android#8]
Initially, we wouldn't want it locked unless there is a specific requirement for it, this is actually a part of the test intention, we would want to see if the data persist is handled properly during the rotation, so let's not hide it out.

**Comment by kodeba** [comment]
The way I handle avoid app losing data when rotate screen
I use "save instance state" and "restore instance state"
for now we have ViewModel it a bit help

but for this project I try to unlock screen orientation 
and on DetailActivity layout going weird 
because I didn't plan to support landscape screen

and it need to re-do some stuff so can we let it be like that first

If you worry about my skill to handle thing when rotate screen
you can go to download this app [https://play.google.com/store/apps/details?id=com.xeersoft.selfu&hl=th](url)
and let play it on Video Player Activity
